Source:  (at 1)
  Description:  (at 1)
    ModuleDef: CRC_32_serial (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 1)
        Port: clk, None (at 1)
        Port: rst, None (at 1)
        Port: load, None (at 1)
        Port: d_finish, None (at 1)
        Port: crc_in, None (at 1)
        Port: crc_out, None (at 1)
      Decl:  (at 2)
        Input: clk, False (at 2)
      Decl:  (at 3)
        Input: rst, False (at 3)
      Decl:  (at 4)
        Input: load, False (at 4)
      Decl:  (at 5)
        Input: d_finish, False (at 5)
      Decl:  (at 6)
        Input: crc_in, False (at 6)
      Decl:  (at 7)
        Output: crc_out, False (at 7)
      Decl:  (at 8)
        Reg: crc_out, False (at 8)
      Decl:  (at 9)
        Reg: crc_reg, False (at 9)
          Width:  (at 9)
            IntConst: 31 (at 9)
            IntConst: 0 (at 9)
      Decl:  (at 10)
        Reg: state, False (at 10)
          Width:  (at 10)
            IntConst: 1 (at 10)
            IntConst: 0 (at 10)
      Decl:  (at 11)
        Reg: count, False (at 11)
          Width:  (at 11)
            IntConst: 5 (at 11)
            IntConst: 0 (at 11)
      Decl:  (at 12)
        Parameter: idle, False (at 12)
          Rvalue:  (at 12)
            IntConst: 2'b00 (at 12)
      Decl:  (at 13)
        Parameter: compute, False (at 13)
          Rvalue:  (at 13)
            IntConst: 2'b01 (at 13)
      Decl:  (at 14)
        Parameter: finish, False (at 14)
          Rvalue:  (at 14)
            IntConst: 2'b10 (at 14)
      Always:  (at 15)
        SensList:  (at 15)
          Sens: posedge (at 15)
            Identifier: clk (at 15)
        Block: None (at 16)
          CaseStatement:  (at 17)
            Identifier: state (at 17)
            Case:  (at 18)
              Identifier: idle (at 18)
              Block: None (at 18)
                IfStatement:  (at 19)
                  Identifier: load (at 19)
                  NonblockingSubstitution:  (at 20)
                    Lvalue:  (at 20)
                      Identifier: state (at 20)
                    Rvalue:  (at 20)
                      Identifier: compute (at 20)
                  NonblockingSubstitution:  (at 22)
                    Lvalue:  (at 22)
                      Identifier: state (at 22)
                    Rvalue:  (at 22)
                      Identifier: idle (at 22)
            Case:  (at 24)
              Identifier: compute (at 24)
              Block: None (at 24)
                IfStatement:  (at 25)
                  Identifier: d_finish (at 25)
                  NonblockingSubstitution:  (at 26)
                    Lvalue:  (at 26)
                      Identifier: state (at 26)
                    Rvalue:  (at 26)
                      Identifier: finish (at 26)
                  NonblockingSubstitution:  (at 28)
                    Lvalue:  (at 28)
                      Identifier: state (at 28)
                    Rvalue:  (at 28)
                      Identifier: compute (at 28)
            Case:  (at 30)
              Identifier: finish (at 30)
              Block: None (at 30)
                IfStatement:  (at 31)
                  Eq:  (at 31)
                    Identifier: count (at 31)
                    IntConst: 32 (at 31)
                  NonblockingSubstitution:  (at 32)
                    Lvalue:  (at 32)
                      Identifier: state (at 32)
                    Rvalue:  (at 32)
                      Identifier: idle (at 32)
                  NonblockingSubstitution:  (at 34)
                    Lvalue:  (at 34)
                      Identifier: count (at 34)
                    Rvalue:  (at 34)
                      Plus:  (at 34)
                        Identifier: count (at 34)
                        IntConst: 1 (at 34)
      Always:  (at 38)
        SensList:  (at 38)
          Sens: posedge (at 38)
            Identifier: clk (at 38)
          Sens: negedge (at 38)
            Identifier: rst (at 38)
        IfStatement:  (at 39)
          Identifier: rst (at 39)
          Block: None (at 40)
            NonblockingSubstitution:  (at 41)
              Lvalue:  (at 41)
                Identifier: count (at 41)
              Rvalue:  (at 41)
                IntConst: 5'b0_0000 (at 41)
            NonblockingSubstitution:  (at 42)
              Lvalue:  (at 42)
                Identifier: state (at 42)
              Rvalue:  (at 42)
                Identifier: idle (at 42)
          CaseStatement:  (at 45)
            Identifier: state (at 45)
            Case:  (at 46)
              Identifier: idle (at 46)
              Block: None (at 46)
                NonblockingSubstitution:  (at 47)
                  Lvalue:  (at 47)
                    Partselect:  (at 47)
                      Identifier: crc_reg (at 47)
                      IntConst: 31 (at 47)
                      IntConst: 0 (at 47)
                  Rvalue:  (at 47)
                    IntConst: 32'b0000_0000_0000_0000_0000_0000_0000_0000 (at 47)
            Case:  (at 49)
              Identifier: compute (at 49)
              Block: None (at 49)
                NonblockingSubstitution:  (at 51)
                  Lvalue:  (at 51)
                    Pointer:  (at 51)
                      Identifier: crc_reg (at 51)
                      IntConst: 0 (at 51)
                  Rvalue:  (at 51)
                    Xor:  (at 51)
                      Pointer:  (at 51)
                        Identifier: crc_reg (at 51)
                        IntConst: 31 (at 51)
                      Identifier: crc_in (at 51)
                NonblockingSubstitution:  (at 52)
                  Lvalue:  (at 52)
                    Pointer:  (at 52)
                      Identifier: crc_reg (at 52)
                      IntConst: 1 (at 52)
                  Rvalue:  (at 52)
                    Pointer:  (at 52)
                      Identifier: crc_reg (at 52)
                      IntConst: 0 (at 52)
                NonblockingSubstitution:  (at 53)
                  Lvalue:  (at 53)
                    Pointer:  (at 53)
                      Identifier: crc_reg (at 53)
                      IntConst: 2 (at 53)
                  Rvalue:  (at 53)
                    Xor:  (at 53)
                      Xor:  (at 53)
                        Pointer:  (at 53)
                          Identifier: crc_reg (at 53)
                          IntConst: 1 (at 53)
                        Pointer:  (at 53)
                          Identifier: crc_reg (at 53)
                          IntConst: 31 (at 53)
                      Identifier: crc_in (at 53)
                NonblockingSubstitution:  (at 54)
                  Lvalue:  (at 54)
                    Partselect:  (at 54)
                      Identifier: crc_reg (at 54)
                      IntConst: 30 (at 54)
                      IntConst: 3 (at 54)
                  Rvalue:  (at 54)
                    Partselect:  (at 54)
                      Identifier: crc_reg (at 54)
                      IntConst: 29 (at 54)
                      IntConst: 2 (at 54)
                NonblockingSubstitution:  (at 55)
                  Lvalue:  (at 55)
                    Pointer:  (at 55)
                      Identifier: crc_reg (at 55)
                      IntConst: 31 (at 55)
                  Rvalue:  (at 55)
                    Xor:  (at 55)
                      Xor:  (at 55)
                        Pointer:  (at 55)
                          Identifier: crc_reg (at 55)
                          IntConst: 30 (at 55)
                        Pointer:  (at 55)
                          Identifier: crc_reg (at 55)
                          IntConst: 31 (at 55)
                      Identifier: crc_in (at 55)
                NonblockingSubstitution:  (at 56)
                  Lvalue:  (at 56)
                    Identifier: crc_out (at 56)
                  Rvalue:  (at 56)
                    Identifier: crc_in (at 56)
            Case:  (at 58)
              Identifier: finish (at 58)
              Block: None (at 58)
                NonblockingSubstitution:  (at 59)
                  Lvalue:  (at 59)
                    Identifier: crc_out (at 59)
                  Rvalue:  (at 59)
                    Pointer:  (at 59)
                      Identifier: crc_reg (at 59)
                      IntConst: 31 (at 59)
                NonblockingSubstitution:  (at 60)
                  Lvalue:  (at 60)
                    Partselect:  (at 60)
                      Identifier: crc_reg (at 60)
                      IntConst: 31 (at 60)
                      IntConst: 0 (at 60)
                  Rvalue:  (at 60)
                    Concat:  (at 60)
                      Partselect:  (at 60)
                        Identifier: crc_reg (at 60)
                        IntConst: 30 (at 60)
                        IntConst: 0 (at 60)
                      IntConst: 1'b0 (at 60)